FROM node:20-alpine AS build

WORKDIR /app/frontend

ARG VITE_API_URL=
ENV VITE_API_URL=$VITE_API_URL

COPY src/frontend/package.json ./
COPY src/frontend/package-lock.json ./
RUN npm ci

COPY src/frontend ./

RUN npm run build

FROM nginx:alpine AS runtime

WORKDIR /usr/share/nginx/html
COPY --from=build /app/frontend/dist ./

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

